### ISSUE TITLE
label names could use review

### ISSUE THREAD

**Issue by aaronkreisberg** [rubyhg/issues-lab-4#2]
https://github.com/rubyhg/issues-lab-4/blob/5dbe58a2373d174a0414c45b7ccc14358d9afd0b/got_issues.Rmd#L34-L35

The x-axis has some random capitalization, maybe lower case the random capitals at the end of the title "Storm Category"

The y-axis title got use some capitalization:  "Air Pressure at Storm Center (millibars)"

**Comment by rubyhg** [comment]
Much better - changed to your suggestions
